<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WdbgToolkit.Core\WdbgToolkit.Core.csproj" />
    <ProjectReference Include="..\WdbgToolkit.PackageManagement\WdbgToolkit.PackageManagement.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
